### ISSUE TITLE
cmake and inlcude path

### ISSUE THREAD

**Issue by Bamban** [OPAE/intel-fpga-bbb#1]
Hi,
I tried to install both OPAE and BBB tools with a local prefix (~/local/opt/intel).
The installation of OPAE went OK. I have everything needed under my prefix, more particularly I have .../include/opae/fpga.h.

When following the build instruction for BBB_cci_mpf/sw, I ran into some isuue.
When first doing `cmake .. -DCMAKE_INSTALL_PREFIX=~/local/opt/intel`, cmake does not find opae/fpga.h, which is perfectly ok because I gave him no clue on where the previous installation is. As I know nothing about Cmake, I opened the CMakeLists.txt 'just to see". And I saw: on line 78 and 79, there are variables that are suited with a prefix. So I filled them but it had no effect, opae/fpga.h was still not found.
I had some hint to make an `export C_INCLUDE_PATH=myprefix` before cmake and it worked.
So my issue is: maybe there is some information missing about how to deal with prefixed installations?
Anyway, thanks for the OPAE suite !

**Comment by michael-adler** [comment]
Fixed on master. ${CMAKE_INSTALL_PREFIX}/include is now added to the search path during the MPF software build setup. Note that if this is the only way the build finds opae/fpga.h then the install path isn't on the default include paths. In your project you will have to ensure that opae/fpga.h is available.
