### ISSUE TITLE
mmio read warning in reading MFP VTP (virtual to physical) statistics 

### ISSUE THREAD

**Issue by Yang-YiFan** [OPAE/intel-fpga-bbb#14]
I have used /samples/tutorial/03_linked_list/sw/linked_list.cpp line 169-184 to read MPF VTP statistics from my afu (I also use the example framework which contains /samples/tutorial/base). In my previous version of afu design this warning didn't pop out. In the latest version the FPGA side terminal pops this warning.

![warning](https://user-images.githubusercontent.com/22767536/37655167-7a153604-2c7f-11e8-8ebf-ccab965b8236.png)

The warning occurs near the end of the simulation. As you can see from the screenshot buffer deallocation is in progress. After I commented out the line 169-184 cpp code in linked_list.cpp. There is no more warning.

I tracked the signal in VCS and found that the in c2.tx port mmio read response valid signal is 1 while mmio read response data contains X bits. After endless tracing, I found that the mmio read response data signal is connected to `events.vtp_out_pt_walk_last_vaddr` in cci_mpf_shim_csr module,  which is finally connected to `translate_va` in cci_mpf_svc_vtp_pt_walk module. `translate_va` is further connected to `lookup_req.pageVA` in cci_mpf_svc_vtp_pipe module. After that I gave up......

Another clue is that only the last mmio read has this warning. Which means other mmio request requested by  line 169-184 cpp code in linked_list.cpp from cpu side is correctly executed. After the last correctly executed mmio read response(which is the second last mmio read response in the system), signal translate_va changes to X. So it makes the last mmio read response invalid (contains X bits). By the way my afu has no mmio read response logic.

I wonder if this is a bug or simply my mistake somewhere. Thank you!

**Comment by michael-adler** [comment]
There are some races between the ASE RTL simulation and the connected software as the two processes are torn down. We have fixed many, but some remain. Once the ASE RTL simulation starts freeing shared buffers and prints its summary you should probably just ignore any errors and assume they are simulation artifacts.

Thank you for pointing this case out. We will look at it at some point, though it won't get high priority.

**Comment by Yang-YiFan** [comment]
Thank you for your reply! For now I just uncomment the software code and ignore the warning since this issue doesn't affect the main functionality of the afu.
