### ISSUE TITLE
OPAE  simulation tools often crash!!!

### ISSUE THREAD

**Issue by eyeloveu** [OPAE/intel-fpga-bbb#17]
I often get this error when running simulations. Especially more often when the design becomes more complicated.
![_20180326112605](https://user-images.githubusercontent.com/29499271/37885650-1078b8c4-30e9-11e8-99c0-0a2bad8b0206.png)

**Comment by Yang-YiFan** [comment]
I have encountered similar issue when I tried to add a fifo (which is an IP generated by Quartus Prime 16.0) in my afu design in some cases. Sometimes by adding some logic not related to this fifo I can actually avoid this error. But this problem sometimes emerges and sometimes just disappear when I add some other logic..... I still can't figure out why this issue sometimes happens while sometimes not.

**Comment by michael-adler** [comment]
Are you both HARP users? If so, these sorts of problems are better addressed at the [HARP forum](https://communities.intel.com/groups/harp).

Are you using a supported environment and simulator version? We haven't seen those SEGVs in our environment. Supported versions for OPAE 0.9.0 are listed [here](https://opae.github.io/docs/ase_userguide/ase_userguide.html). The version requirements for AAL SR-5.0.3 are similar.
