### ISSUE TITLE
include syntax in sources.txt is confusing

### ISSUE THREAD

**Issue by eyeloveu** [OPAE/intel-fpga-bbb#38]
1. During opae 0.9.0, include source list is written like this in BBB:
SI:../../../base/hw/sim/base_addenda.txt
QI:../../../base/hw/par/cci_examples_base_PAR_files.qsf

2. In BBB's wiki/Installation, it is written like this:
# Include MPF
-F $FPGA_BBB_CCI_SRC/BBB_cci_mpf/hw/sim/cci_mpf_sim_addenda.txt
# Include clock crossing FIFO
-F $FPGA_BBB_CCI_SRC/BBB_ccip_async/hw/sim/ccip_async_sim_addenda.txt
## Import MPF and async FIFO libraries
source $::env(FPGA_BBB_CCI_SRC)/BBB_cci_mpf/hw/par/qsf_cci_mpf_PAR_files.qsf
source $::env(FPGA_BBB_CCI_SRC)/BBB_ccip_async/hw/par/ccip_async_addenda.qsf

3. In the latest BBB's tutorial, it is written like this:
C:../../../base/hw/rtl/base_sources.txt

I think it is a little bit confusing and messy, which is the final and working version and should I follow? Are there any instructions?

**Comment by michael-adler** [comment]
Thank you for pointing out the inconsistency. I will update the Wiki.

The new method in base_sources.txt is the recommended way to import the BBS sources, though either way will work. Both methods ultimately load the same configuration files.

**Comment by eyeloveu** [comment]
@michael-adler Got it! Thanks for your quick answer.
