### ISSUE TITLE
Question related to License header 

### ISSUE THREAD

**Issue by saitej25** [OPAE/intel-fpga-bbb#42]
While using the CCIP_MUX I've realized there are file with Intel Confidential as License Header. Can I use them leverage these codes in my development ?
PS: The solution we are building will be vendor agnostic, so we should be able to use these codes for Xilinx Products.

**Comment by michael-adler** [comment]
Yes, you may use them. Those licenses are a mistake and we will replace them with the MIT/BSD license used in the rest of the repository.

**Comment by michael-adler** [comment]
Fixed.

**Comment by saitej25** [comment]
Thanks
