### ISSUE TITLE
VC Map unexpected behaviour under heavy stress

### ISSUE THREAD

**Issue by diorga** [OPAE/intel-fpga-bbb#54]
# Problem description
I have written two coherency tests to better understand the behaviours that are disallowed with the MPF is enabled. These tests are focused on the "VC Map" shim which should make requests that go to the same address use the same channel, which should provide coherent accesses. I am basing this on the [VC Map documentation](https://github.com/OPAE/intel-fpga-bbb/wiki/BBB_cci_mpf) which states: *VC Map: Often used in combination with WRO — a mechanism for avoiding inter-physical channel ordering problems that would normally require write fences*

The litmus tests are
```
// coWR
// x- shared memory location, r- register
// Initial state : x==0
x = 1
r = x
// Disallowed final state r == 0
```
```
// coWW
// x - shared memory location
// Initial state x==0
x = 1
x = 2
// Disallowed final state x == 1
```
When I run these tests on a Broadwell Xeon+FPGA using opae, I have observed several instances where the disallowed final state is observed. I only see this when a lot of extra traffic is added. The exact implementation of the tests is more clearly described bellow and in the README files of each test, which I have attached as a .zip.

I am curious, is this behaviour intended? Is there a way to instantiate the MPF such that this behaviour is disallowed? Thanks in advance!

## Tests
The experiment will be repeated REPETITIONS times. The stress is created with a high volume of read and and write requests. The first enemy sends every A clock cycles a write and read request to channel VL0, the second enemy sends every B clock cycles a write and read request to channel VH0 and the third enemy sends every C clock cycles a write and read request to channel VH1.

The enemies run concurrently with the FPGA. If two or more requests occur in the same clock cycle only the FPGA test can make the request and the enemy will be ignored.

The expanded version of this test is:
### coWR
```
// CPU  Thread:
1. Allocate x[REPETITIONS+1] in shared memory
2. Allocate result[2] in shared memory
3. x[0, ..., REPETITIONS] <- 0
4. result[0,1] <- -1
5. Memory fence
6. Send address of "x" to FPGA via CSR
7. Send address of "result" to FPGA via CSR
8. Start the FPGA
9. Spin, waiting result to change value

   // FPGA test:                           | // FPGA VL0 enemy            | // FPGA VH0 enemy         | // FPGA VH1 enemy
   1. temp_0 = 0;                          | if VL0 enemy enabled         | if VH0 enemy enabled      | if VH1 enemy enabled
   2. temp_1 = 0;                          |   every clock A cycle        |   every clock B cycle     |   every clock C cycle
   3. for(i=1; i<REPETITIONS+1; i++)       |     VL0: WriteReq Addr x[0]  |     VH0: Write Addr x[0]  |     VH1: Write Addr x[0]
      4. VA: WriteReq, Addr x[i], data = 1 |     VL0: ReadReq Addr x[0]   |     VH0: Read Addr x[0]   |     VH1: Read Addr x[0]
      5. VA: WriteRsp                      |                              |                           |
      6. VA: ReadReq, Addr x[i]            |                              |                           |
      7. VA: ReadRsp, Data = r             |                              |                           |
      7. if (r == 1) temp_1++;             |                              |                           |
      8. if (r == 0) temp_0++;             |                              |                           |
   9. endfor                               |                              |                           |
   10. write temp_0 to r[0]                |                              |                           |
   11. write temp_1 to r[1]                |                              |                           |

// CPU Thread
10. Display the histogram stored in r
```

Finally; is it possible for r[0] to be non-zero?

### Experiments
NOTE:
 * Before synthesis, make sure that BBB_CCI_SRC in base/hw/par/cci_mpf_test_base_PAR_files points to the MPF location.
 * Before simulation, the PATHS need to be updated in base/hw/sim/cci_mpf_test_base_addenda.txt

#### Experiment 1
Running experiment without any interference:
```
# Run the test without any interference
./coWR_FPGA -r 10000
```
Output
```
Test
x = 1
r = x
--------------
r = 0 occurred 0 times
r = 1 occurred 10000 times
VL0 20008 : VH0 0 : VH1 0
```
Test behaves as expected, traffic only on channel VL0

#### Experiment 2
Running experiment with interference:
```
# Every 20 clock cycles emit a random write and read request on VL0
./coWR_FPGA -r 10000 --VLO_enemy 20
```

Output:
```
Test
x = 1
r = x
--------------
r = 0 occurred 0 times
r = 1 occurred 10000 times
VL0 435791 : VH0 15 : VH1 0
```
Test behaves as expected, traffic on channel VL0 and some on VH0 but the final result is correct.

#### Experiment 3

```
# Every 20 clock cycles emit a random write and read request on VL1
# Every 10 clock cycles emit a random write and read request on VH1
./coWR_FPGA -r 10000 --VL0_enemy 20 --VH0_enemy 10
```

Output:
```
Test
x = 1
r = x
--------------
r = 0 occurred 1547 times
r = 1 occurred 8453 times
VL0 1693719 : VH0 2976274 : VH1 388

```

This is unexpected behaviour.

### coWW

```
// CPU  Thread:
1. Allocate x[REPETITIONS+1] in shared memory
2. Allocate result[2] in shared memory
3. x[0, ..., REPETITIONS] <- 0
4. result <- -1
5. Memory fence
6. Send address of "x" to FPGA via CSR
7. Send address of "result" to FPGA via CSR
8. Start the FPGA
9. Spin, waiting result to change value
   // FPGA test                             | // FPGA VLO enemy           | // FPGA VH0 enemy        | //FPGA VH1 enemy
   1. temp_0 = 0;                           | if VL0 enemy enabled        | if VH0 enemy enabled     | if VH1 enemy enabled
   2. temp_1 = 0;                           |   every clock A cycle       |   every clock B cycle    |   every clock C cycle
   3. for(i=1; i<REPETITIONS+1; i++)        |     VL0: WriteReq Addr x[0] |     VH0: Write Addr x[0] |     VH1: Write Addr x[0]
      4. VA: WriteReq1, Addr x[i], data = 1 |     VL0: ReadReq Addr x[0]  |     VH0: Read Addr x[0]  |     VH1: Read Addr x[0]
      5. VA: WriteRsp1                      |                             |                          |  
      6. VA: WriteReq2, Addr x[i], Data = 2 |                             |                          |
      7. VA: WriteRsp2, Data = r            |                             |                          |
   8. endfor                                |                             |                          |
   9. write sync to r                       |                             |                          |
                                            |                             |                          |
                                            |                             |                          |
                                            |                             |                          |
10. Read contents of x array
11. Display the histogram of values


```
Finally; is it possible for any element of the array to be 1?

#### Experiment 1
Running experiment without any interference:
```
# Run the test without any interference
./coWW_FPGA -r 10000
```
Output
```
Test
x = 1
x = 2
--------------
r = 1 occurred 0 times
r = 2 occurred 10000 times
VL0 20008 : VH0 0 : VH1 0
```
Test behaves as expected, traffic only on channel VL0

#### Experiment 2
Running experiment with interference:
```
# Every 20 clock cycles emit a random write and read request on VL0
./coWR_FPGA -r 10000 --VLO_enemy 20
```

Output:
```
Test
x = 1
x = 2
--------------
r = 0 occurred 0 times
r = 1 occurred 10000 times
VL0 446117 : VH0 29 : VH1 0
```
Test behaves as expected, traffic on channel VL0 and some on VH0 but the final result is correct.

#### Experiment 3

```
# Every 20 clock cycles emit a random write and read request on VL1
# Every 10 clock cycles emit a random write and read request on VH1
./coWR_FPGA -r 10000 --VL0_enemy 20 --VH0_enemy 10
```

Output:
```
Test
x = 1
x = 2
--------------
r = 1 occurred 58 times
r = 2 occurred 9942 times
VL0 671628 : VH0 1165444 : VH1 520

```

This is unexpected behaviour.

## Source code
The source code can be found here: [bug.zip](https://github.com/OPAE/intel-fpga-bbb/files/4716435/bug.zip)

**Comment by diorga** [comment]
Based on internal discussions with developers, we have concluded that the issue likely steps from virtual channel mappings, which are not a priority to implement in future chips. Thus, there is limited value in exploring this issue further at this time

**Comment by Yang-YiFan** [comment]
@diorga btw in our practice, without the write reordering MPF enabled, if we explicitly map the writes to two VH channels (PCIe), we observed that the write order is preserved. But our experiment is not conducted at a particularly high load scenario, so the situation might be different in your case.
