### ISSUE TITLE
Publish Spec for BBB-CCI-GEMM

### ISSUE THREAD

**Issue by srivatsankrishnan** [OPAE/intel-fpga-bbb#8]
Hi,
Can you publish the spec/documentation for BBB-CCI-GEMM?
Thanks
Sri

**Comment by michael-adler** [comment]
Yes, we should. Whoever has it, please don't put it in the repository here. PDF and other large files should go elsewhere. Sri, can you send e-mail to me with details of where it is and who has it?

**Comment by michael-adler** [comment]
Documentation is now in the Wiki: [BBB_cci_gemm](https://github.com/OPAE/intel-fpga-bbb/wiki/BBB_cci_gemm).
